server:
  port: 8100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_store_dev
    username: root
    password: root

jwt:
  secret: qwertyuiopasdfghjklzxcvbnmqwertyuioh
  expiration: 86400
  time:
    delete-tokens: 60000
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: C:\Users\maxim\Repozinory\onlineStore\online-store\auth-server\src\main\resources\spring.log
